# Java
# Package your Java project.
# Add steps that install, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: '$(SourceBranchName)-$(Build.SourceVersion)-Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - master

  tags:
    include:
      - v*

pr:
  autoCancel: true
  branches:
    include:
      - master

variables:
  ${{ if eq( variables['Build.Reason'], 'PullRequest') }}:
    environment: 'sbox'
    env.upper: 'SBOX'
  ${{ if ne( variables['Build.Reason'], 'PullRequest') }}:
    environment: 'test' #Uset test and promoting to stg until prod is ready
    env.upper: 'TEST'
  application.name: 'mi-azurite'
  azure.container.registry: 'ssprivate$(env).azurecr.io'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.upper)'

resources:
  repositories:
    - repository: mi-core
      type: github
      name: hmcts/mi-core-lib
      endpoint: hmcts

stages:
  - template: pipeline-steps/templates/docker-build.yaml@mi-core
    parameters:
      azureContainerRegistry: $(azure.container.registry)
      azureSubscriptionEndpoint: $(azure.subscription.endpoint)
      applicationName: $(application.name)
